### VARS
@host=http://127.0.0.1:8000
@username=root
@password=1

###
# @name root-api
GET {{host}} HTTP/1.1
content-type: application/json

###
# @name auth
POST {{host}}/accounts/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}
###
@token = {{auth.response.body.$.access}}

###
# @name signup
POST {{host}}/accounts/signup/
Content-Type: application/json

{
    "username": "test{{$randomInt 10 1000}}",
    "password": "tre12345"
}

@newUserNameId = {{signup.response.body.$.id}}

###
# @name postsList
GET {{host}}/posts/ HTTP/1.1
Content-type: application/json
Authorization: Bearer {{token}}

###
# @name postCreate
POST {{host}}/posts/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Post {{$randomInt 10 10000}}",
    "body": "Post body {{$randomInt 10 10000}}",
    "user": "root"
}

@postId = {{postCreate.response.body.$.id}}

###
# @name postDetail
GET {{host}}/posts/{{postId}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name postDelete
DELETE {{host}}/posts/{{postId}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name likeList
GET {{host}}/likes/
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name addLike
POST {{host}}/likes/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "post": "{{postId}}",
    "users": ["{{username}}"],
}

###
# @name dislikeList
GET {{host}}/dislikes/
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name addDislike
POST {{host}}/dislikes/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "post": "{{postId}}",
    "users": ["{{username}}"]
}

###
# @name analytics
GET {{host}}/api/analytics
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{token}}

date_from=2020-04-11&date_to=2020-04-11