# Generated by Django 3.0.5 on 2020-04-14 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20200414_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='users',
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.AddField(
            model_name='dislike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Dislike user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Like user'),
            preserve_default=False,
        ),
    ]
