# Generated by Django 3.0.5 on 2020-04-15 08:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_auto_20200414_1608'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user')},
        ),
    ]
